= アプリケーションネットワークの表示
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Visualizer を使用して、アプリケーションネットワークのグラフを表示します。

アプリケーションネットワークのトポロジは、Anypoint Visualizer によって自動的に生成されます。視覚化を見やすくするため、コンシューマノード 
(アウトバウンド接続のみのノード) が上部に表示され、すべてのバックエンドシステム (インバウンド接続のみのノード) が下部に表示されます。コンシューマノードで `ClientId` が検出された場合、`ClientId`  でグループ化されます。それ以外の場合、*[External Traffic (外部トラフィック)]* ノードの下でグループ化されます。
 `ClientId` が検出されるには、対象の `application/API/proxy` に *[Client Id enforcement (クライアント ID 適用)]* ポリシーが設定されている必要があります。

グラフを表示または変更するときに、Anypoint Visualizer で次の機能を使用できます。

* 変更を元に戻すまたはやり直す: キャンバスの左下隅にある元に戻すボタンとやり直しボタンを使用して、変更を元に戻したりやり直したりできます。
* ズームコントロール: キャンバスの右下隅にあるズームインボタン、ズームアウトボタン、サイズに合わせたズームボタンを使用して、ズームを制御します。スクロールを使用してズームインおよびズームアウトすることもできます。
* 視覚化のパン: キャンバスをクリックしてドラッグし、視覚化をパンします。

== 組織のアプリケーションネットワークの表示

. Management Center から、*[Visualizer]* を選択します。
+
Visualizer が使用できない場合は、システム管理者に連絡して、アプリケーションにアクセスするための適切な権限があることを確認してください。

. サイドパネルの環境検索条件で、環境を選択します。
+
Anypoint Visualizer には、参照権限がある環境のみが表示されます。

. 表示するビジネスグループのチェックボックスをクリックします。

組織と環境グループを選択したら、Anypoint Visualizer にアプリケーションネットワークのグラフが表示されます。

== ネットワーク内のすべてのノードに関する情報の表示

キャンバスの左上隅にあるドロップダウンを使用して、アプリケーションネットワーク内のすべてのノードについて表示する指標と時間枠を選択します。
1 つのドロップダウンで、次の指標のいずれかを選択できます。

* *Inbound connections (インバウンド接続)*
* *Errors count (エラー数)*
* *avg. response time (平均応答時間)*
* *avg. throughput (平均スループット)*
* *avg. CPU consumption (平均 CPU 消費量)*
* *avg. memory utilization (平均メモリ使用量)*

もう一方のドロップダウンでは、選択した指標の平均値の計算に使用される時間枠を選択できます。

数値が長くなることを避けるために、Anypoint Visualizer は単位のプレフィックスを使用してビューを簡略化します。たとえば、次のように表示されます

|===
| Avg throughput (平均スループット) | 66.7m TPM | 66.7 million transactions per minute (1 分あたり 6,670 万トランザクション) | 0.0667 TPM
|===
https://en.wikipedia.org/wiki/Metric_prefix[指標プレフィックスの簡単な説明はここ]にありますが、Anypoint Visualizer では、*u* は *μ*  ではなくマイクロを表します。.

== ネットワーク内の 1 つのノードに関する情報の表示

グラフ内のノードを選択すると、そのノードとその連動関係スタックが強調表示され、接続されていないすべてのノードはグレー表示されます。 Anypoint Visualizer の右側のパネルには、ノードに関する情報が表示されます。このパネルは次のセクションに分割されています。

* *Details (詳細)*: ノードに関する情報が表示されます。
* *Metrics summary (指標の概要)*: 選択されたノードで監視している指標が表示されます。指標には、[Errors count (エラー数)]、[avg. response time (平均応答時間)]、[avg. throughput (平均スループット)]、[avg.CPU consumption (平均 CPU 消費量)]、[avg. memory utilization (平均メモリ使用量)] があります。
* *Metrics chart (指標グラフ)*: *[Metric (指標)]* ドロップダウンで選択した指標の時系列グラフが表示されます。

* *Customization (カスタマイズ)*: ノードが割り当てられているレイヤとそのノードに割り当てられているタグに関する情報が表示されます。このセクションから、レイヤとタグを変更できます。xref:layers.adoc[「Anypoint Visualizer でのレイヤの使用」]およびxref:use-tags-in-visualizer.adoc[「Anypoint Visualizer でのタグの使用」]を参照してください。.

サイドパネルから、*[Rename Node (ノード名を変更)]* をクリックしてノードの名前を変更できます。

*[Search services (サービスを検索)]* テキスト項目で、ノード (サービス) を検索できます。

== ネットワーク内の接続に関する情報の表示

グラフ内の接続を選択すると、Anypoint Visualizer の右側のパネルにその接続に関する基本情報が表示されます。

サイドパネルから、*[Set Edge Name (エッジ名を設定)]* ボタンをクリックして接続の名前を変更できます。

[メモ]
サービス間に表示されるエッジはアクティブです。つまり、過去 7 日間にトラフィックがあった場合にのみ表示されます。非アクティブなエッジはキャンバスに表示されません。


[[customize-view]]
== ネットワークのビューのカスタマイズ

サイドパネルの絞り込み機能を使用してビューをカスタマイズし、キャンバスに何が表示されるかを選択します。環境、タグ、およびサービスで絞り込むことができます。

この機能により、グラフに表示したくないノードを非表示にできます。検索条件の選択は、変更するまで保持されます。Anypoint Visualizer を閉じて後でキャンバスを再読み込みすると、最後に行った検索条件の選択が表示されます。

検索条件はカスケード設計であるため、選択された環境またはタグに属さないすべてのノードは自動的にサービスのリストで非表示になります。*[Show dependents and dependencies (連動と連動関係を表示)]*  を切り替えると、サービスと共に、選択したタグを使用するノードとサービスの連動関係が表示されます。 右側のパネルとキャンバスが更新され、現在の選択内容が表示されます。


== 関連情報

* xref:layers.adoc[Anypoint Visualizer でのレイヤの使用]
* xref:use-tags-in-visualizer.adoc[Anypoint Visualizer でのタグの使用]
